server:
  port: 8080
  servlet:
    session:
      #Session???????5???????????30??
      timeout: 18000
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=America/Costa_Rica&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: amy1121
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    # ???????
    suffix: .ftl
    # ??????
    content-type: text/html
    # ????????
    charset: UTF-8
    # ??????
    cache: true
    settings:
      number_format: 0.##
  web:
    resources:
      static-locations: classpath:static/,file:static/


mybatis-plus:
  type-aliases-package: com.example.blog.entity
  configuration:
    call-setters-on-nulls: false
    #????
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: ASSIGN_UUID
      logic-not-delete-value: 1
      logic-delete-value: 0


logging:
  level:
    root: info